name: moneychat
description: The objective of this project is to develop an app where users can chat with their contacts and able send and receive money from their digital wallet. Also, users can check their account details and view all past transactions.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/